# Generated by Django 3.2.4 on 2021-07-27 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesadmin',
            old_name='titla',
            new_name='title',
        ),
    ]
